version: "3"

volumes:
  data:

networks:
  traefik:
    external: true

services:
  dbushell:
    container_name: dbushell
    image: ghcr.io/dbushell/ubuntu
    restart: unless-stopped
    command: >-
      zsh -c "npm install --no-save
      && npm run build:deno
      && npm start"
    networks:
      - traefik
    volumes:
      - data:/home/user
      - ./bin:/home/user/bin
      - ./src:/home/user/src
      - ./public:/home/user/public
      - ./package.json:/home/user/package.json
      - ./netlify.toml:/home/user/netlify.toml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dbushell.rule=Host(`dbushell.localhost`)"
      - "traefik.http.services.dbushell.loadbalancer.server.port=8080"
