networks:
  traefik:
    external: true

volumes:
  data:
    name: dbushell

services:
  dbushell:
    container_name: dbushell
    image: ghcr.io/dbushell/ubuntu
    restart: unless-stopped
    command: /home/user/src/init.sh
    networks:
      - traefik
    volumes:
      - data:/home/user
      - ./bin:/home/user/bin
      - ./src:/home/user/src
      - ./public:/home/user/public
      - ./netlify.toml:/home/user/netlify.toml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dbushell.rule=Host(`dbushell.localhost`)"
      - "traefik.http.services.dbushell.loadbalancer.server.port=8080"
