[build]
  publish = "./public"
  command = "npm run build:prod"

[context.production]
  environment = { NODE_ENV = "production", NODE_VERSION = "15.11" }

[[headers]]
  for = "*.avif"
  [headers.values]
    Content-Type = "image/avif"
    Content-Disposition = "inline"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31557600"
    Content-Security-Policy = "default-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'; connect-src 'self' https://*.eu-west-1.amazonaws.com; img-src 'self' data:; script-src 'self' 'sha256-CTGifSILACIBZiHQWNvPwazIcE0JmTtquHurH2ee+m4='; style-src 'self' 'sha256-Eq6udzQeVZJL/VfB7HS/sq/h8eWbBTVYTzbj8pTObq8=' 'sha256-XrKcNZy1uCtwrhydUGyFDLAyZlDk6UdePGVIuffI6T0=';"
    Referrer-Policy = "same-origin"

[[redirects]]
  from = "/demos/*"
  to = "/?demo=:splat"
  status = 302
  force = false

[[redirects]]
  from = "/Nestable*"
  to = "http://dbushell.github.io/Nestable/"
  status = 301
  force = false

[[redirects]]
  from = "/Pikaday*"
  to = "https://pikaday.com/:splat"
  status = 301
  force = false
