[build]
  publish = "./public"
  command = "npm run build:prod"

[[headers]]
  for = "*.avif"
  [headers.values]
    Content-Type = "image/avif"
    Content-Disposition = "inline"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "frame-ancestors 'none'"

[[redirects]]
  from = "/demos/*"
  to = "/?demo=:splat"
  status = 302
  force = false

[[redirects]]
  from = "/Nestable*"
  to = "http://dbushell.github.io/Nestable/"
  status = 301
  force = false

[[redirects]]
  from = "/Pikaday*"
  to = "https://pikaday.com/:splat"
  status = 301
  force = false
