[build]
  publish = "./public"
  command = "./src/netlify/build.sh"

[functions]
  directory = "./src/netlify/functions"

[[headers]]
  for = "*.avif"
  [headers.values]
    Content-Type = "image/avif"
    Content-Disposition = "inline"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31557600"
    Content-Security-Policy = "default-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'; connect-src 'self'; img-src 'self' data:; script-src 'self' 'sha256-EBNM/KJbAcZ+IENXduu+InfRbtXGh9uk4ZE7cnOn/bI='; style-src 'self' 'sha256-j8YKGkZ0x7ellRlqvm24B+B6zeZrthO5uoyBWGia0fA=' 'sha256-M7Z/R6azUsoNM77aBWHJTgS5MSuVEK3Z9MymhafpGcY=';"
    Referrer-Policy = "same-origin"
    Permissions-Policy = "interest-cohort=()"

[[redirects]]
  from = "/demos/*"
  to = "/?demo=:splat"
  status = 302
  force = false

[[redirects]]
  from = "/Nestable*"
  to = "http://dbushell.github.io/Nestable/"
  status = 301
  force = false

[[redirects]]
  from = "/Pikaday*"
  to = "https://pikaday.com/:splat"
  status = 301
  force = false
