[build]
  publish = "./public"
  command = "./src/deno/netlify.sh"
  # command = "npm run build"

[functions]
  directory = "./src/netlify/functions"

# [context.production]
#   environment = { NODE_ENV = "production", NODE_VERSION = "15.11" }

# [context.deploy-preview]
#   environment = { NODE_ENV = "production", NODE_VERSION = "15.11" }

# [context.branch-deploy]
#   environment = { NODE_ENV = "production", NODE_VERSION = "15.11" }

[[headers]]
  for = "*.avif"
  [headers.values]
    Content-Type = "image/avif"
    Content-Disposition = "inline"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31557600"
    Content-Security-Policy = "default-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'; connect-src 'self'; img-src 'self' data:; script-src 'self' 'sha256-N5kelC4mILbf1FMWCbPgJT8tPLGacg59JEhz+E7lBXw='; style-src 'self' 'sha256-59MdrupwSRElEUM8Sl3R9nWNRhLEz8yke+NeX9flVqw=' 'sha256-M7Z/R6azUsoNM77aBWHJTgS5MSuVEK3Z9MymhafpGcY=';"
    Referrer-Policy = "same-origin"
    Permissions-Policy = "interest-cohort=()"

[[redirects]]
  from = "/demos/*"
  to = "/?demo=:splat"
  status = 302
  force = false

[[redirects]]
  from = "/Nestable*"
  to = "http://dbushell.github.io/Nestable/"
  status = 301
  force = false

[[redirects]]
  from = "/Pikaday*"
  to = "https://pikaday.com/:splat"
  status = 301
  force = false
